image: 'gitpod/workspace-full'

tasks:
  - name: 'docker-daemon'
    init: 'cp .env.example .env && npm install --global npm@7 && npm ci'
    command: 'sudo docker-up'
  - name: 'docker-container'
    init: 'echo "Waiting for docker daemon to start" &&
      until docker info &> /dev/null; do sleep 1; done;'
    command: 'docker-compose up'

ports:
  - port: 3000
    onOpen: 'open-preview'

  - port: 1080
    onOpen: 'notify'

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: true
