image: 'gitpod/workspace-full'

tasks:
  - name: 'docker-daemon'
    before: 'cp .env.example .env && npm install --global npm@7 && npm install'
    init: 'sudo docker-up'
  - name: 'docker-container'
    before: 'echo "Waiting for docker daemon to start" &&
      until docker info &> /dev/null; do sleep 1; done;'
    init: 'docker-compose up'

ports:
  - port: 3000
    onOpen: 'open-preview'

  - port: 1080
    onOpen: 'notify'
