version: '3.0'
services:
  divlo.fr-website:
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: './'
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: ${PORT}
    volumes:
      - './:/app'
