version: '3.0'
services:
  divlo.fr:
    container_name: ${COMPOSE_PROJECT_NAME}
    image: 'divlo.fr'
    build:
      context: './'
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: ${PORT}
