name: 'Release'

on:
  workflow_run:
    workflows: [Divlo]
    branches: [master]
    types:
      - 'completed'

jobs:
  release:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: 'actions/checkout@v2'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v2.1.5'
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Cache dependencies'
        uses: 'actions/cache@v2.1.5'
        with:
          path: '.npm'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - run: 'npm install --global npm@7'
      - run: 'npm ci --cache .npm --prefer-offline'
      - run: 'npm run release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
